server {
    listen 80;
    root /app;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript text/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|ico|svg|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
